// this file was autogenerated by "yarn g:types" for version 2023-04-28
// do not edit it manually

/**
 * A short summary of the applicant's career goals and achievements
 */
export type ProfessionalSummary = null | string;
/**
 * A statement that the applicant gives permission to process their data
 */
export type DataProcessingPermission = null | string;
/**
 * Width of the image in pixels
 */
export type WidthInPixels = number;
/**
 * Height of the image in pixels
 */
export type HeightInPixels = number;
/**
 * Name of the organization
 */
export type OrganizationName = string;
/**
 * Logo of the organization
 */
export type OrganizationLogo = Image | null;
/**
 * Location of the job
 */
export type Location = string;
/**
 * Start date of the job
 */
export type StartDate = string;
/**
 * End date of the job
 */
export type EndDate = null | string;
/**
 * List of work experiences
 *
 * @maxItems 25
 */
export type Experience = Experience1[];
/**
 * List of educational experiences
 *
 * @maxItems 10
 */
export type Education =
  | []
  | [Education1]
  | [Education1, Education1]
  | [Education1, Education1, Education1]
  | [Education1, Education1, Education1, Education1]
  | [Education1, Education1, Education1, Education1, Education1]
  | [Education1, Education1, Education1, Education1, Education1, Education1]
  | [Education1, Education1, Education1, Education1, Education1, Education1, Education1]
  | [Education1, Education1, Education1, Education1, Education1, Education1, Education1, Education1]
  | [Education1, Education1, Education1, Education1, Education1, Education1, Education1, Education1, Education1]
  | [
      Education1,
      Education1,
      Education1,
      Education1,
      Education1,
      Education1,
      Education1,
      Education1,
      Education1,
      Education1
    ];
/**
 * Logo of the school or university
 */
export type SchoolLogo = Image | null;
/**
 * Degree
 */
export type Degree = "Associate" | "Bachelor" | "Master" | "Doctorate" | "Postdoc" | null;
/**
 * Major
 */
export type Major = string;
/**
 * Name of the institution
 */
export type Institution = string;
/**
 * Start date of the education
 */
export type StartDate1 = string;
/**
 * End date of the education
 */
export type EndDate1 = null | string;
/**
 * Grade point average
 */
export type GPA = null | number;
/**
 * Whether the education is finished
 */
export type Finished = boolean;
/**
 * List of certifications
 *
 * @maxItems 10
 */
export type Certifications =
  | []
  | [Certification]
  | [Certification, Certification]
  | [Certification, Certification, Certification]
  | [Certification, Certification, Certification, Certification]
  | [Certification, Certification, Certification, Certification, Certification]
  | [Certification, Certification, Certification, Certification, Certification, Certification]
  | [Certification, Certification, Certification, Certification, Certification, Certification, Certification]
  | [
      Certification,
      Certification,
      Certification,
      Certification,
      Certification,
      Certification,
      Certification,
      Certification
    ]
  | [
      Certification,
      Certification,
      Certification,
      Certification,
      Certification,
      Certification,
      Certification,
      Certification,
      Certification
    ]
  | [
      Certification,
      Certification,
      Certification,
      Certification,
      Certification,
      Certification,
      Certification,
      Certification,
      Certification,
      Certification
    ];
/**
 * Name of the certification
 */
export type CertificationName = string;
/**
 * Date the certification was received
 */
export type DateReceived = null | string;
/**
 * Date the certification is valid until
 */
export type ValidUntil = null | string;
/**
 * List of projects
 *
 * @maxItems 15
 */
export type Projects =
  | []
  | [Project]
  | [Project, Project]
  | [Project, Project, Project]
  | [Project, Project, Project, Project]
  | [Project, Project, Project, Project, Project]
  | [Project, Project, Project, Project, Project, Project]
  | [Project, Project, Project, Project, Project, Project, Project]
  | [Project, Project, Project, Project, Project, Project, Project, Project]
  | [Project, Project, Project, Project, Project, Project, Project, Project, Project]
  | [Project, Project, Project, Project, Project, Project, Project, Project, Project, Project]
  | [Project, Project, Project, Project, Project, Project, Project, Project, Project, Project, Project]
  | [Project, Project, Project, Project, Project, Project, Project, Project, Project, Project, Project, Project]
  | [
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project
    ]
  | [
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project
    ]
  | [
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project,
      Project
    ];
/**
 * Image of the project
 */
export type ProjectImage = Image | null;
/**
 * Organization that the project belongs to
 */
export type OrganizationWhereTheProjectWasDone = Organization1 | null;
/**
 * Name of the project
 */
export type ProjectName = string;
/**
 * Description of the project
 */
export type ProjectDescription = string | null;
/**
 * Start date of the project
 */
export type StartDate2 = string;
/**
 * End date of the project
 */
export type EndDate2 = null | string;
/**
 * Link to the project
 */
export type ProjectLink = null | string;
/**
 * Tags for the project
 *
 * @maxItems 25
 */
export type ProjectTags = string[];
/**
 * List of languages
 *
 * @maxItems 15
 */
export type Languages =
  | []
  | [Skill]
  | [Skill, Skill]
  | [Skill, Skill, Skill]
  | [Skill, Skill, Skill, Skill]
  | [Skill, Skill, Skill, Skill, Skill]
  | [Skill, Skill, Skill, Skill, Skill, Skill]
  | [Skill, Skill, Skill, Skill, Skill, Skill, Skill]
  | [Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill]
  | [Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill]
  | [Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill]
  | [Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill]
  | [Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill]
  | [Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill]
  | [Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill]
  | [Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill, Skill];
/**
 * Type of the skill
 */
export type SkillType = "Language" | "Framework" | "Library" | "Database" | "Platform" | "Other";
/**
 * Name of the skill
 */
export type SkillName = string;
/**
 * Proficiency of the skill expressed as a number between 0 and 100
 */
export type SkillProficiency = number;
/**
 * List of skills
 *
 * @maxItems 30
 */
export type Skills = Skill[];
/**
 * List of awards and honors
 *
 * @maxItems 20
 */
export type AwardsAndHonors =
  | []
  | [AwardOrHonor]
  | [AwardOrHonor, AwardOrHonor]
  | [AwardOrHonor, AwardOrHonor, AwardOrHonor]
  | [AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor]
  | [AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor]
  | [AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor]
  | [AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor]
  | [AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor, AwardOrHonor]
  | [
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor
    ]
  | [
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor
    ]
  | [
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor
    ]
  | [
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor
    ]
  | [
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor
    ]
  | [
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor
    ]
  | [
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor
    ]
  | [
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor
    ]
  | [
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor
    ]
  | [
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor
    ]
  | [
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor
    ]
  | [
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor,
      AwardOrHonor
    ];
/**
 * Name of the award or honor
 */
export type AwardOrHonorName = string;
/**
 * Image of the award or honor
 */
export type AwardOrHonorImage = Image | null;
/**
 * Organization that issued the award or honor
 */
export type AwardOrHonorIssuer = Organization1 | null;
/**
 * Date the award or honor was received
 */
export type DateReceived1 = null | string;
/**
 * Description of the award or honor
 */
export type AwardOrHonorDescription = null | string;
/**
 * Tags for the award or honor
 *
 * @maxItems 25
 */
export type AwardOrHonorTags = string[];
/**
 * List of volunteer experiences
 *
 * @maxItems 20
 */
export type VolunteerExperience =
  | []
  | [VolunteerExperience1]
  | [VolunteerExperience1, VolunteerExperience1]
  | [VolunteerExperience1, VolunteerExperience1, VolunteerExperience1]
  | [VolunteerExperience1, VolunteerExperience1, VolunteerExperience1, VolunteerExperience1]
  | [VolunteerExperience1, VolunteerExperience1, VolunteerExperience1, VolunteerExperience1, VolunteerExperience1]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ]
  | [
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1,
      VolunteerExperience1
    ];
/**
 * Role in the volunteer experience
 */
export type VolunteerExperienceRole = string;
/**
 * Organization that the volunteer experience belongs to
 */
export type VolunteerExperienceOrganization = Organization1 | null;
/**
 * Location of the volunteer experience
 */
export type VolunteerExperienceLocation = null | string;
/**
 * Start date of the volunteer experience
 */
export type VolunteerExperienceStartDate = null | string;
/**
 * End date of the volunteer experience
 */
export type VolunteerExperienceEndDate = null | string;
/**
 * Description of the volunteer experience
 */
export type VolunteerExperienceDescription = null | string;
/**
 * Tags for the volunteer experience
 *
 * @maxItems 25
 */
export type VolunteerExperienceTags = string[];
/**
 * Name of the reference provider
 */
export type ReferenceProviderName = string;
/**
 * URL of the reference provider
 */
export type ReferenceProviderURL = string;
/**
 * Phone number of the issuer
 */
export type PhoneNumber = null | string;
/**
 * Email of the issuer
 */
export type Email = null | string;
/**
 * Organization where applicant worked with the issuer
 */
export type Organization2 = Organization1 | null;
/**
 * Description of the reference
 */
export type ReferenceDescription = string;
/**
 * List of references
 *
 * @maxItems 25
 */
export type References = Reference[];

/**
 * Open Resume Format (ORF) schema
 */
export interface Resume {
  /**
   * The version of resume schema in format of date (YYYY-MM-DD)
   */
  version: string;
  professionalSummary: ProfessionalSummary;
  dataProcessingPermission: DataProcessingPermission;
  personalInformation: PersonalInformation;
  experience: Experience;
  education: Education;
  certifications: Certifications;
  projects: Projects;
  languages: Languages;
  skills: Skills;
  awardsAndHonors: AwardsAndHonors;
  volunteerExperience: VolunteerExperience;
  references: References;
  /**
   * Additional attributes of the resume, used also for custom plugins configuration
   */
  attributes: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Personal information of the applicant
 */
export interface PersonalInformation {
  /**
   * Links to social profiles, etc.
   *
   * @maxItems 5
   */
  links?: [] | [Link] | [Link, Link] | [Link, Link, Link] | [Link, Link, Link, Link] | [Link, Link, Link, Link, Link];
  /**
   * Image of the applicant
   */
  image: Image | null;
  /**
   * Full name of the applicant
   */
  fullName: string;
  /**
   * Email address
   */
  email: string;
  /**
   * Phone number in international format
   */
  phoneNumber: null | string;
  /**
   * Address, city, country, etc.
   */
  address: null | string;
  /**
   * Interests, hobbies, etc.
   */
  interests: null | string;
  [k: string]: unknown;
}
export interface Link {
  url: string;
  title: string;
  [k: string]: unknown;
}
/**
 * Image. Used for personal information, experience, etc. URL may be also a base64 encoded image
 */
export interface Image {
  /**
   * URL or base64 of the image
   */
  url: string;
  /**
   * Alternative text for the image
   */
  alt?: null | string;
  width?: WidthInPixels;
  height?: HeightInPixels;
  [k: string]: unknown;
}
/**
 * Work experience
 */
export interface Experience1 {
  image: Image | null;
  /**
   * Job title
   */
  jobTitle: string;
  organization: Organization;
  location: Location;
  startDate: StartDate;
  endDate: EndDate;
  /**
   * Description of the job
   */
  description: string;
  /**
   * @maxItems 25
   */
  tags: string[];
  [k: string]: unknown;
}
/**
 * Organization
 */
export interface Organization {
  name: OrganizationName;
  url: null | string;
  image: OrganizationLogo;
  [k: string]: unknown;
}
export interface Education1 {
  image: SchoolLogo;
  degree: Degree;
  major: Major;
  institution: Institution;
  startDate: StartDate1;
  endDate: EndDate1;
  gpa: GPA;
  finished: Finished;
  [k: string]: unknown;
}
export interface Certification {
  name: CertificationName;
  issuer: CertificationIssuer;
  dateReceived: DateReceived;
  validUntil: ValidUntil;
  /**
   * @maxItems 25
   */
  tags: string[];
  [k: string]: unknown;
}
/**
 * Organization that issued the certification
 */
export interface CertificationIssuer {
  name: OrganizationName;
  url: null | string;
  image: OrganizationLogo;
  [k: string]: unknown;
}
export interface Project {
  image: ProjectImage;
  organization: OrganizationWhereTheProjectWasDone;
  projectName: ProjectName;
  description: ProjectDescription;
  startDate: StartDate2;
  endDate: EndDate2;
  projectLink: ProjectLink;
  tags: ProjectTags;
  [k: string]: unknown;
}
/**
 * Organization
 */
export interface Organization1 {
  name: OrganizationName;
  url: null | string;
  image: OrganizationLogo;
  [k: string]: unknown;
}
/**
 * Skill that the person has
 */
export interface Skill {
  type: SkillType;
  name: SkillName;
  proficiency: SkillProficiency;
  [k: string]: unknown;
}
/**
 * Award or honor that the person has received
 */
export interface AwardOrHonor {
  awardName: AwardOrHonorName;
  image: AwardOrHonorImage;
  organization: AwardOrHonorIssuer;
  dateReceived: DateReceived1;
  description: AwardOrHonorDescription;
  tags: AwardOrHonorTags;
  [k: string]: unknown;
}
export interface VolunteerExperience1 {
  role: VolunteerExperienceRole;
  organization: VolunteerExperienceOrganization;
  location: VolunteerExperienceLocation;
  startDate: VolunteerExperienceStartDate;
  endDate: VolunteerExperienceEndDate;
  description: VolunteerExperienceDescription;
  tags: VolunteerExperienceTags;
  [k: string]: unknown;
}
export interface Reference {
  issuer: ReferenceIssuer;
  organization: Organization2;
  description: ReferenceDescription;
  [k: string]: unknown;
}
/**
 * Person or organization that issued the reference
 */
export interface ReferenceIssuer {
  name: ReferenceProviderName;
  url: ReferenceProviderURL;
  phoneNumber?: PhoneNumber;
  email?: Email;
  [k: string]: unknown;
}
