// this file is autogenerated by "yarn g:versions"
// do not edit it manually
export type OpenResumeVersion = 'latest'
    | '2023-04-28';

export const openResumeLatestVersion: OpenResumeVersion = '2023-04-28';

export const openResumeVersions: OpenResumeVersion[] = [
    '2023-04-28'
];
